name_set["robot"] = [
    "Pracownik Automata X9",
    "Primaron",
    "Robolus",
    "Cybercil",
    "Kofish",
    "Aceroly",
    "Antissbone",
    "Retron",
    "Ramshade",
    "Notobot",
    "Nirion",
    "Moron",
    "Hydronomix",
    "Anaroux",
    "Tajet",
    "Vinus",
    "Nestation",
    "Nexorion",
    "Virutus",
    "Thylene",
    "Fireriox",
    "Alarion",
    "Thunderpath",
    "Alphastar",
    "Necrodrate",
    "Ana-V",
    "Roble",
    "Ligon",
    "Proport",
    "Modonate",
    "Combon",
    "Valryuner",
    "Gungrenlant",
    "Hulking Gaigelzen",
    "Kaiwadten V",
    "Hulking Gerwaden-Oh",
    "Metal Godgergern Z",
    "Gunvolan",
    "Metal Gekigelphon Robo",
    "Goryudeen Go",
    "Brave Gungarten the Brave",
    "Gekidaner",
    "Gungaosion 3",
    "Metal Gogerbot",
    "Godjinger the Brave",
    "Great Gekikailant",
    "Iron Gekijinar",
    "Gaigaoger",
    "Iron Gekigaiter",
    "King Gerzingbuster",
    "Godraiphon the Brave",
    "Gaodanter",
    "Goreizam 3",
    "Metal Gundammarg",
    "Gaoreimarg",
    "Steel Gogaision",
    "Gairyuter",
    "Gaogereon",
    "Goddamphon",
    "Gundanen V",
    "EVE",
    "CHARLIE",
    "S.A.M.",
    "BEN",
    "R.I.C. 2.0",
    "HAL 9001",
    "EDI",
    "Marvin",
    "Tik-Tok",
    "RB-1",
    "Andromeda",
    "Curiosity",
    "T-802",
    "Anne Droid"
];