window.generalData = {
    "artifacts": [
        { "name": "Antidepressiva tabletter", "weight": 1 },
        { "name": "Armborst", "weight": 1 },
        { "name": "Automatkarbin", "weight": 1 },
        { "name": "Automatpistol", "weight": 1 },
        { "name": "Batteri", "weight": 1 },
        { "name": "Bensindunk", "weight": 1 },
        { "name": "Dagbok (metaplot)", "weight": 1 },
        { "name": "Gasmask", "weight": 1 },
        { "name": "Generator", "weight": 1 },
        { "name": "Gitarr", "weight": 1 },
        { "name": "Hagelgevär", "weight": 1 },
        { "name": "Handgranat", "weight": 1 },
        { "name": "Hockeyhjälm", "weight": 1 },
        { "name": "ID-kort (metaplot)", "weight": 1 },
        { "name": "Jaktgevär", "weight": 1 },
        { "name": "Kamouflageuniform", "weight": 1 },
        { "name": "Kanot", "weight": 1 },
        { "name": "Karta över Zonen", "weight": 1 },
        { "name": "Katana", "weight": 1 },
        { "name": "Kassettradio (metaplot)", "weight": 1 },
        { "name": "Kikare", "weight": 1 },
        { "name": "Klänning", "weight": 1 },
        { "name": "Kompass", "weight": 1 },
        { "name": "Konstverk", "weight": 1 },
        { "name": "Kostym", "weight": 1 },
        { "name": "Livsstilsmagasin", "weight": 1 },
        { "name": "Luftmadrass", "weight": 1 },
        { "name": "Lugnande medel", "weight": 1 },
        { "name": "Läskburk", "weight": 1 },
        { "name": "Löpsedel 1", "weight": 1 },
        { "name": "Löpsedel 2", "weight": 1 },
        { "name": "Löpsedel 1", "weight": 1 },
        { "name": "Moped", "weight": 1 },
        { "name": "Motorbåt", "weight": 1 },
        { "name": "Motorsåg", "weight": 1 },
        { "name": "Mountainbike", "weight": 1 },
        { "name": "Paraply", "weight": 1 },
        { "name": "Parfymflaska", "weight": 1 },
        { "name": "Personbil", "weight": 1 },
        { "name": "Pilbåge", "weight": 1 },
        { "name": "REGEN", "weight": 1 },
        { "name": "Revolver", "weight": 1 },
        { "name": "Rökgranat", "weight": 1 },
        { "name": "Serietidning", "weight": 1 },
        { "name": "Signalpistol", "weight": 1 },
        { "name": "Skiftnyckel", "weight": 1 },
        { "name": "Skottsäker väst", "weight": 1 },
        { "name": "Skyddsdräkt", "weight": 1 },
        { "name": "Smärtstillande tabletter", "weight": 1 },
        { "name": "Solglasögon", "weight": 1 },
        { "name": "Strålkastare", "weight": 1 },
        { "name": "Uppåttjack", "weight": 1 },
        { "name": "Videokamera (metaplot)", "weight": 1 },
        { "name": "Bildvisir", "weight": 1 },
        { "name": "Boxningshandskar", "weight": 1 },
        { "name": "Chockbatong", "weight": 1 },
        { "name": "Cigarettlimpa", "weight": 1 },
        { "name": "Cigarettändare", "weight": 1 },
        { "name": "Elektronikverktyg", "weight": 1 },
        { "name": "Energigranat", "weight": 1 },
        { "name": "Fotoalbum", "weight": 1 },
        { "name": "Fyrverkerier", "weight": 1 },
        { "name": "Fåtölj", "weight": 1 },
        { "name": "Förbandslåda", "weight": 1 },
        { "name": "Hockeymask", "weight": 1 },
        { "name": "Hockeyskydd", "weight": 1 },
        { "name": "Kaffebryggare", "weight": 1 },
        { "name": "Kaffepaket", "weight": 1 },
        { "name": "Kravallsköld", "weight": 1 },
        { "name": "Laserpistol", "weight": 1 },
        { "name": "Maserpistol", "weight": 1 },
        { "name": "MC-hjälm", "weight": 1 },
        { "name": "Megafon", "weight": 1 },
        { "name": "MMO-kub", "weight": 1 },
        { "name": "Nylonrep", "weight": 1 },
        { "name": "Polaroidkamera", "weight": 1 },
        { "name": "ROBDES-karbin", "weight": 1 },
        { "name": "Silvertejp", "weight": 1 },
        { "name": "Skinnpaj", "weight": 1 },
        { "name": "Slalomutrustning", "weight": 1 },
        { "name": "Snöskoter", "weight": 1 },
        { "name": "Spikpistol", "weight": 1 },
        { "name": "Teddybjörn", "weight": 1 },
        { "name": "Vattenskoter", "weight": 1 },
        { "name": "Båtmotor", "weight": 1 },
        { "name": "Dykardräkt", "weight": 1 },
        { "name": "Flytväst", "weight": 1 },
        { "name": "Harpun", "weight": 1 },
        { "name": "Kastspö", "weight": 1 },
        { "name": "Luftkompressor", "weight": 1 }
    ],
    "weapons": [
        {
            "type": "Närstrid",
            "name": "Tillhygge",
            "bonus": 1,
            "skada": 1,
            "reach": "Armslängd",
            "kommentar": []
        }, {
            "type": "Närstrid",
            "name": "Skrotkniv",
            "bonus": 1,
            "skada": 2,
            "reach": "Armslängd",
            "kommentar": []
        }, {
            "type": "Närstrid",
            "name": "Skrotklubba",
            "bonus": 2,
            "skada": 1,
            "reach": "Armslängd",
            "kommentar": []
        }, {
            "type": "Närstrid",
            "name": "Chockbatong",
            "bonus": 2,
            "skada": 1,
            "reach": "Armslängd",
            "kommentar": ["Ger T6 stress.", "Energivapen."]
        }, {
            "type": "Närstrid",
            "name": "Lasersvets",
            "bonus": 2,
            "skada": 2,
            "reach": "Armslängd",
            "kommentar": ["Lätt vapen.", "Energivapen."]
        }, {
            "type": "Närstrid",
            "name": "Vibrokniv",
            "bonus": 2,
            "skada": 2,
            "reach": "Armslängd",
            "kommentar": ["Ger T6 stress.", "Energivapen.", "Ignorerar pansar."]
        }, {
            "type": "Närstrid",
            "name": "Stridssåg",
            "bonus": 2,
            "skada": 3,
            "reach": "Armslängd",
            "kommentar": ["Energivapen."]
        }, {
            "type": "Avstånd",
            "name": "Chockpistol",
            "bonus": 2,
            "skada": 2,
            "reach": "Kort",
            "kommentar": ["Lätt vapen.", "Energivapen.", "Ger stress istället för skada."]
        }, {
            "type": "Avstånd",
            "name": "Laserpistol",
            "bonus": 3,
            "skada": 2,
            "reach": "Lång",
            "kommentar": ["Lätt vapen.", "Energivapen."]
        }, {
            "type": "Avstånd",
            "name": "Lasergevär",
            "bonus": 3,
            "skada": 2,
            "reach": "Distans",
            "kommentar": ["Energivapen."]
        }, {
            "type": "Avstånd",
            "name": "Maserpistol",
            "bonus": 2,
            "skada": 3,
            "reach": "Kort",
            "kommentar": ["Lätt vapen.", "Energivapen."]
        }, {
            "type": "Avstånd",
            "name": "Plasmakarbin",
            "bonus": 2,
            "skada": 3,
            "reach": "Lång",
            "kommentar": ["Energivapen."]
        }
    ]
}