window.nameData = {
    "en": {
        "nameSpacer": " ",
        "plural": "'s",
        "people": {
            "mittlander": {
                "prefix": [
                    "bren",
                    "bran",
                    "edel",
                    "edil",
                    "eid",
                    "eo",
                    "gul",
                    "gal",
                    "guld",
                    "gul",
                    "hedel",
                    "her",
                    "log",
                    "mau",
                    "maug",
                    "mor",
                    "mord"
                ],
                "suffix": {
                    "male": [
                        "ard",
                        "bard",
                        "jar",
                        "gjar",
                        "ed",
                        "hed",
                        "finn",
                        "fraidh",
                        "han",
                        "marr",
                        "red",
                        "rik",
                        "win",
                        "winn"
                    ],
                    "female": [
                        "non",
                        "annon",
                        "de",
                        "elde",
                        "eid",
                        "heid",
                        "trude",
                        "itrude",
                        "frid",
                        "lynn",
                        "na",
                        "nhja",
                        "rynn",
                        "wa",
                        "wen"
                    ]
                }
            },
            "stormlander": {
                "prefix": [
                    "as",
                    "bod",
                    "bryn",
                    "hall",
                    "hraf",
                    "ing",
                    "jor",
                    "tor",
                    "vig",
                    "vret"
                ],
                "suffix": {
                    "male": [
                        "biorn",
                        "geir",
                        "grim",
                        "galt",
                        "jald",
                        "orm",
                        "ulf",
                        "ur",
                        "vald",
                        "varr"
                    ],
                    "female": [
                        "a",
                        "dis",
                        "dott",
                        "gerd",
                        "hild",
                        "umbla",
                        "unn",
                        "veig",
                        "vida",
                        "vigg"
                    ]
                },
                "lastnames": {
                    "epithets": [
                        "nidslayer",
                        "trollchopper",
                        "bloodspreader"
                    ],
                    "profession": [
                        "smith",
                        "farmer",
                        "boatbuilder",
                        "logger"
                    ],
                    "nickname": [
                        "tamper",
                        "askew nose",
                        "harelip",
                        "trolleye"
                    ]
                }
            },
            "virann": {
                "prefix": [
                    "ber",
                    "beor",
                    "bur",
                    "buor",
                    "bewr",
                    "bewor",
                    "brun",
                    "bruni",
                    "bran",
                    "brani",
                    "bron",
                    "broni",
                    "donni",
                    "dunni",
                    "ed",
                    "edel",
                    "ev",
                    "evel",
                    "fri",
                    "fride",
                    "fra",
                    "frade",
                    "fru",
                    "frude",
                    "gal",
                    "gals",
                    "gol",
                    "gols",
                    "hun",
                    "huni",
                    "hen",
                    "heni",
                    "klod",
                    "klodi",
                    "klud",
                    "kludi",
                    "mer",
                    "mero",
                    "mor",
                    "moro",
                    "ro",
                    "rode",
                    "ru",
                    "rude",
                    "sor",
                    "sork",
                    "sar",
                    "sark",
                    "sul",
                    "suli",
                    "sol",
                    "soli",
                    "sal",
                    "sali",
                    "tryn",
                    "tryni",
                    "tron",
                    "troni"
                ],
                "suffix": {
                    "male": [
                        "bad",
                        "gar",
                        "gist",
                        "kar",
                        "kind",
                        "kull",
                        "pis",
                        "red",
                        "rik",
                        "till",
                        "thill",
                        "walan",
                        "vard",
                        "wig",
                        "vik"
                    ],
                    "female": [
                        "th",
                        "dith",
                        "fing",
                        "gond",
                        "hed",
                        "hedd",
                        "kild",
                        "len",
                        "mynt",
                        "mynta",
                        "nell",
                        "sta",
                        "stai",
                        "strid",
                        "thne",
                        "tilde",
                        "winda"
                    ]
                },
                "lastnames": {
                    "family": ["no family names in list"],
                    "epithets": [
                        "magekiller",
                        "trollchopper",
                        "heathencrusher"
                    ],
                    "profession": [
                        "smith",
                        "farmer",
                        "breeder",
                        "logger"
                    ],
                    "nickname": [
                        "tamper",
                        "askew nose",
                        "harelip",
                        "trolleye"
                    ]
                }
            },
            "wildfolk": {
                "prefix": [],
                "suffix": {
                    "male": [],
                    "female": []
                }
            },
            "elf": {
                "prefix": [
                    "harp",
                    "jep",
                    "jeppi",
                    "kyll",
                    "lep",
                    "lepo",
                    "norma",
                    "normo",
                    "pojh",
                    "pojha",
                    "sirp",
                    "sirpa",
                    "syll",
                    "vaj",
                    "vajne",
                    "val",
                    "vali"
                ],
                "suffix": {
                    "male": [
                        "hang",
                        "ehang",
                        "iaho",
                        "piaho",
                        "akka",
                        "ingas",
                        "jias",
                        "lainen",
                        "mojna",
                        "pihi",
                        "taja",
                        "ua"
                    ],
                    "female": [
                        "ala",
                        "pala",
                        "atta",
                        "hiska",
                        "ika",
                        "iulu",
                        "iullu",
                        "kosva",
                        "lajna",
                        "likki",
                        "olvi",
                        "sinka"
                    ]
                }
            },
            "dwarf": {
                "prefix": [
                    "bor",
                    "brok",
                    "dvor",
                    "fifun",
                    "glo",
                    "gly",
                    "jo",
                    "jor",
                    "niful",
                    "ru",
                    "ruk",
                    "tjeb",
                    "tor",
                    "zvor"
                ],
                "suffix": {
                    "male": [
                        "olgd",
                        "dolga",
                        "ka",
                        "kka",
                        "ust",
                        "rust",
                        "drank",
                        "gel",
                        "linkk",
                        "logi",
                        "rovv",
                        "van",
                        "var",
                        "zink"
                    ]
                }
            },
            "troll": {
                "prefix": [
                    "a",
                    "nak",
                    "gnak",
                    "wart",
                    "wort",
                    "ort",
                    "sludge",
                    "lou",
                    "loud",
                    "e",
                    "fart",
                    "fish",
                    "foul",
                    "grog",
                    "furm",
                    "gri",
                    "grik",
                    "grinn",
                    "pig",
                    "hog",
                    "ke",
                    "claw",
                    "curl",
                    "wee",
                    "gnat"
                ],
                "suffix": [
                    "lork",
                    "lorsk",
                    "louse",
                    "mo",
                    "must",
                    "sapp",
                    "ogg",
                    "fur",
                    "roar",
                    "reak",
                    "snitch",
                    "poach",
                    "snuff",
                    "stink",
                    "mare",
                    "fa",
                    "fat",
                    "teet",
                    "teeth",
                    "tide",
                    "tangle",
                    "snarl",
                    "urg",
                    "wise",
                    "yge",
                    "ygel",
                    "yt"
                ]
            },
            "lastnames": {
                "lineage": [
                    "swaahndril",
                    "swaansjhoe",
                    "culihan",
                    "gunnrahoel",
                    "navorna",
                    "gwendan",
                    "luwndhinn",
                    "lehwgrhein",
                    "wallhin",
                    "ahlbwerg",
                    "ahlgrhein",
                    "ahlsthra",
                    "beehkmarn",
                    "bweergdahan",
                    "bwierger",
                    "bwerglihn",
                    "bweerglundha"
                ],
                "heroic": {
                    "prefix": [
                        "wyrm",
                        "troll",
                        "wind"
                    ],
                    "suffix": [
                        "slayer",
                        "chopper",
                        "rider",
                    ]
                },
                "peasant": {
                    "profession": [
                        "smith",
                        "farmer",
                        "breeder",
                        "logger"
                    ],
                    "nickname": [
                        "tamper",
                        "askew nose",
                        "harelip",
                        "trolleye"
                    ]
                }
            }
        },
        "place": {
            "town": {
                "prefix": [
                    "alder",
                    "elf",
                    "ash",
                    "atla",
                    "aud",
                    "audur",
                    "bjalfe",
                    "bjorn",
                    "birch",
                    "placid",
                    "blut",
                    "buck",
                    "borke",
                    "brage",
                    "brase",
                    "bronja",
                    "bale",
                    "egil",
                    "ejlög",
                    "oak",
                    "ese",
                    "fair",
                    "falcon",
                    "frost",
                    "gad",
                    "boar",
                    "gaute",
                    "gerd",
                    "gisle",
                    "toil",
                    "gorm",
                    "grim",
                    "pig",
                    "mine",
                    "grey",
                    "gyda",
                    "hammer",
                    "sanctify",
                    "hall",
                    "hrim",
                    "hall",
                    "jon",
                    "jorna",
                    "jot",
                    "iron",
                    "jökull",
                    "jöt",
                    "bleak",
                    "kjole",
                    "copper",
                    "raven",
                    "raven",
                    "twig",
                    "laupe",
                    "small",
                    "lynx",
                    "laud",
                    "marsk",
                    "mead",
                    "earth",
                    "cloud",
                    "nid",
                    "njal",
                    "odd",
                    "snake",
                    "east",
                    "oster",
                    "rafner",
                    "rauk",
                    "runic",
                    "silver",
                    "scour",
                    "smith",
                    "sun",
                    "soot",
                    "stron",
                    "stone",
                    "path",
                    "great",
                    "storm",
                    "strait",
                    "pine",
                    "twinkle",
                    "troll",
                    "luck",
                    "ulf",
                    "ulm",
                    "unn",
                    "willow",
                    "wild",
                    "winter",
                    "wise",
                    "vhite",
                    "vret",
                    "west",
                    "field",
                    "ridge",
                    "moose",
                    "east"
                ],
                "suffix": [
                    "alder",
                    "anger",
                    "back",
                    "mount",
                    "blut",
                    "shed",
                    "sheddy",
                    "castle",
                    "bottom",
                    "steep",
                    "bridge",
                    "mill",
                    "well",
                    "village",
                    "brook",
                    "valley",
                    "haze",
                    "oath",
                    "fjord",
                    "mountain",
                    "rapids",
                    "frost",
                    "field",
                    "gang",
                    "mouth",
                    "gard",
                    "gold",
                    "farm",
                    "haga",
                    "hall",
                    "hammer",
                    "port",
                    "harg",
                    "heath",
                    "home",
                    "holm",
                    "holt",
                    "hult",
                    "hall",
                    "high",
                    "lodge",
                    "rock",
                    "cliff",
                    "hill",
                    "mill",
                    "spring",
                    "market",
                    "live",
                    "lid",
                    "ling",
                    "grove",
                    "luck",
                    "leaf",
                    "ground",
                    "bog",
                    "monje",
                    "clime",
                    "isthmus",
                    "om",
                    "pass",
                    "row",
                    "room",
                    "rup",
                    "ryd",
                    "grubbed",
                    "sala",
                    "woods",
                    "forest",
                    "sorrow",
                    "sta",
                    "stein",
                    "stone",
                    "way",
                    "log",
                    "strait",
                    "tegn",
                    "thing",
                    "tarn",
                    "thwart",
                    "top",
                    "croft",
                    "swamp",
                    "tun",
                    "tune",
                    "um",
                    "calf",
                    "ley",
                    "vi",
                    "bay",
                    "wind",
                    "virja",
                    "view",
                    "field",
                    "ridge",
                    "river",
                    "meadow"
                ]
            },
            "tavern": {
                "prefix": [
                    "troll",
                    "rot",
                    "snake",
                    "hugg",
                    "skald",
                    "pig",
                    "robber",
                    "mead",
                    "hero",
                    "raven",
                    "storme's",
                    "bronje",
                    "trough",
                    "forest",
                    "ale",
                    "twin",
                    "ravage",
                    "garm",
                    "starving",
                    "listening",
                    "broken",
                    "prancing",
                    "frozen",
                    "brook",
                    "gave",
                    "saga",
                    "beard",
                    "moss",
                    "lichen",
                    "mountain",
                    "fir needle",
                    "dragon",
                    "tender",
                    "frothy",
                    "crazy",
                    "enraged",
                    "slaughtered",
                    "fried",
                    "cooked",
                    "red",
                    "green",
                    "yellow",
                    "white",
                    "black",
                    "brown",
                    "drunken"
                ],
                "suffix": [
                    "hall",
                    "burrow",
                    "den",
                    "sty",
                    "tavern",
                    "hash house",
                    "pig",
                    "bear",
                    "cottage",
                    "home",
                    "hole",
                    "ice hole",
                    "gulf",
                    "tarn",
                    "croft",
                    "mountain",
                    "head",
                    "tower",
                    "crossing",
                    "realm",
                    "place",
                    "point",
                    "boar",
                    "wanderer",
                    "ponny",
                    "buck",
                    "rabbit",
                    "pint",
                    "head",
                    "house",
                    "cat",
                    "snake",
                    "tailor"
                ]
            },
            "river": {
                "prefix": [
                    "troll",
                    "rot",
                    "snake",
                    "lunge",
                    "skald",
                    "pig",
                    "robber",
                    "mead",
                    "hero",
                    "raven",
                    "forest",
                    "ale",
                    "twin",
                    "ravage",
                    "frozen",
                    "beard",
                    "moss",
                    "mountain",
                    "fir needle",
                    "dragon",
                    "tender",
                    "frothy",
                    "crazy",
                    "enraged",
                    "red",
                    "green",
                    "yellow",
                    "white",
                    "black",
                    "brown",
                    "blue",
                    "moaning",
                    "arrowhead",
                    "cold",
                    "ask",
                    "dread",
                    "wondering ",
                    "wandering ",
                    "sunny",
                    "pale",
                    "cloudy",
                    "misty",
                    "climbing",
                    "pirk",
                    "northern",
                    "southern",
                    "eastern",
                    "western",
                    "lifeless",
                    "mesmerizing ",
                    "tranquil ",
                    "rolling"
                ],
                "suffix": [
                    "river",
                    "channel",
                    "stream",
                    "beck",
                    "creek",
                    "crick",
                    "run",
                    "rill",
                    "rindle",
                    "torrent",
                    "flow",
                    "estuary",
                    "fall",
                    "falls",
                    "brook",
                    "rivulet",
                    "elv",
                    "leak"
                ]
            },
            "mountain": {
                "prefix": [
                    "troll",
                    "rot",
                    "snake",
                    "hugg",
                    "skald",
                    "pig",
                    "robber",
                    "hero",
                    "raven",
                    "forest",
                    "ale",
                    "twin",
                    "ravage",
                    "garm",
                    "starving",
                    "listening",
                    "broken",
                    "frozen",
                    "saga",
                    "beard",
                    "moss",
                    "lichen",
                    "fir needle",
                    "dragon",
                    "tender",
                    "crazy",
                    "enraged",
                    "slaughtered",
                    "red",
                    "green",
                    "yellow",
                    "white",
                    "black",
                    "brown",
                    "drunken",
                    "quiet",
                    "dangerous",
                    "moonlit",
                    "unscaled",
                    "lonely",
                    "thundering",
                    "windless",
                    "light",
                    "heavy",
                    "adamantine", "ancient", "angry", "arctic", "arid", "bare", "barren", "beholding", "bellowing",
                    "black", "bronze", "burning", "calm", "calmest", "charmed", "cold", "collapsing",
                    "colossal",
                    "cursed", "dangerous", "dark", "darkest", "dead", "decayed", "decaying", "deserted",
                    "desolate", "desolated", "distant", "dominating", "eastern", "empty",
                    "enchanted", "enormous", "eroded", "ethereal", "ever reaching", "everlasting", "fabled", "faraway",
                    "feared", "fearsome", "flaring", "forbidden", "forested", "fractured", "frightening", "frozen",
                    "gargantuan", "giant", "gigantic", "gloomy", "gold", "golden", "gray", "grim", "haunted",
                    "heaven-reaching", "hollow", "homeless", "hopeless", "huge", "humongous", "hungry", "ice-crowned","ice-troll",
                    "immense", "iron", "isolated", "jagged", "laughing", "lifeless", "light", "lightest",
                    "lonely", "mastomant", "mighty", "mirrored", "misty", "moaning", "monstrous", "moonlit", "motionless",
                    "mysterious", "naked", "narrow", "neverending", "new", "northern", "overhanging", "plain",
                    "prickly", "quiet", "raging", "relentless", "remote", "restless", "rocky", "round-topped",
                    "rugged", "sad", "savage", "scarlet", "severed", "shadowed", "shadowy", "sharp-peaked",
                    "shimmering", "silver", "slumbering", "snowy", "southern", "steep", "terraced",
                    "thundering", "towering", "unresting", "unwelcoming", "vast", "violent",
                    "voiceless", "volcanic", "welcoming", "western", "whispering", "white", "windless", "windy",
                    "wintry", "withered", "yelling"
                ],
                "suffix": [
                    "home",
                    "mountain",
                    "point",
                    "mount",
                    "outcrop",
                    "fell",
                    "hill",
                    "hump",
                    "knoll",
                    "alp",
                    "bluff",
                    "cliff",
                    "peak",
                    "pile",
                    "ridge",
                    "sierra",
                    "bank",
                    "butte",
                    "crag",
                    "dome",
                    "drift",
                    "glob",
                    "heap",
                    "mass",
                    "height",
                    "mesa",
                    "mound",
                    "mount",
                    "pike",
                    "range",
                    "ton",
                    "tor",
                    "stack",
                    "summit",
                    "apex",
                    "brow",
                    "bump",
                    "crown",
                    "pinnacle",
                    "rise",
                    "slopes",
                    "tips",
                    "tops",
                    "crown",
                    "tip"
                ]
            },
            "lake": {
                "prefix": [
                    "troll",
                    "rot",
                    "snake",
                    "pig",
                    "robber",
                    "mead",
                    "hero",
                    "raven",
                    "forest",
                    "ale",
                    "twin",
                    "ravage",
                    "garm",
                    "frozen",
                    "saga",
                    "beard",
                    "moss",
                    "lichen",
                    "mountain",
                    "fir needle",
                    "dragon",
                    "red",
                    "blue",
                    "green",
                    "yellow",
                    "white",
                    "black",
                    "brown",
                    "drunken",
                    "abysmal", "arctic", "arrowhead", "barren", "bland", "boiling", "bottomless", "brilliant", "bursting", "calm", "calmest", "charmed", "cheerless","cold", "crystal", "cursed", "dancing", "dark", "darkest", "dead", "deep", "deepest", "dense", "depraved", "distant", "dragonfly", "dread", "dreaded", "eastern", "emerald", "empty", "enchanted", "ethereal", "fair", "flat", "flowing", "foaming", "forbidden", "frothy", "frozen", "furthest", "glassy", "gleaming", "glistening", "grave", "gray", "green", "harmonious", "harmony", "heartless", "heaving", "hungry", "infinite", "isolated", "laughing", "lifeless", "lilypad", "living", "lonely", "lucent", "majestic", "mesmerizing", "midnight", "mighty", "mirror", "mirrored", "misty", "moaning", "moon-lit", "motionless", "moving", "narrow", "neglected", "new", "northern", "peaceful", "perfumed", "pleasant", "pristine", "quiet", "raging", "rainy", "red", "reflecting", "relaxing", "restless", "rippling", "rocking", "rolling", "rough", "rushing", "salty", "sandy", "savage", "serene", "shaded", "shadow", "shady", "shimmering", "silent", "sleeping", "soundless", "southern", "spacious", "sparkling", "sunny", "surging", "tadpole", "thundering", "tinted", "tranquil", "troubled", "turbulent", "ugly", "uncanny", "unknown", "unstable", "vast", "violent", "walled", "wasted", "wasteful", "wasting", "waveless", "western", "whispering", "white", "wild", "windy", "wondering", "wrinkled", "yearning"
                ],
                "suffix": [
                    "hole",
                    "lake",
                    "gulf",
                    "tarn",
                    "place",
                    "mere",
                    "loch",
                    "lough",
                    "pool",
                    "pond",
                    "millpond",
                    "mouth",
                    "spring",
                    "wells",
                    "basin",
                    "bowl",
                    "pan",
                    "pot",
                    "tub",
                    "dip",
                    "ewer",
                    "sink",
                    "marsh",
                    "shallows",
                    "shoal",
                    "puddle",
                    "dew",
                    "splash",
                    "bath",
                    "anchorage",
                    "firth",
                    "cove",
                    "depths",
                    "gorge",
                    "waters"
                ]
            }
        },
        "thing": {
            "plant": {
                "prefix": [
                    "evening",
                    "fairy",
                    "mountainous",
                    "bjark",
                    "bear",
                    "leaf",
                    "blood",
                    "bloody",
                    "bronze",
                    "dew",
                    "dis",
                    "drake",
                    "dwarf",
                    "mire",
                    "fire",
                    "torch",
                    "fare",
                    "finger",
                    "yarn",
                    "gave",
                    "grim",
                    "grey",
                    "grey",
                    "yellow",
                    "gilded",
                    "hare",
                    "stallion",
                    "heavenly",
                    "hird",
                    "deer",
                    "hop",
                    "hvale",
                    "autumn",
                    "fall",
                    "witch",
                    "leech",
                    "jarl",
                    "earth",
                    "jorn",
                    "jotun",
                    "iron",
                    "giant",
                    "calder",
                    "toffle",
                    "coal",
                    "copper",
                    "raven",
                    "king's",
                    "marsh",
                    "fen",
                    "loon",
                    "grove",
                    "moth",
                    "manna",
                    "constable",
                    "mist",
                    "mirk",
                    "dark",
                    "mire",
                    "moon",
                    "night",
                    "nut",
                    "snake",
                    "ox",
                    "arrow",
                    "powder",
                    "rafner",
                    "rose",
                    "red",
                    "silver",
                    "lake",
                    "sharp",
                    "scuff",
                    "forestry",
                    "drop",
                    "snow",
                    "sun",
                    "stone",
                    "star",
                    "storme",
                    "black",
                    "swine",
                    "thorn",
                    "tallow",
                    "thistle",
                    "fool",
                    "troll",
                    "tree",
                    "mound",
                    "wolf",
                    "water",
                    "wild",
                    "winter",
                    "white",
                    "vitner",
                    "spring",
                    "goblin",
                    "elk",
                    "river",
                    "fairy",
                    "fay",
                    "lea",
                    "field",
                    "meadow"
                ],
                "suffix": [
                    "anise",
                    "apple",
                    "spike",
                    "bark",
                    "beet",
                    "brightly",
                    "leaf",
                    "bloom",
                    "flower",
                    "bracken",
                    "bush",
                    "berry",
                    "bean",
                    "chicory",
                    "dill",
                    "oak",
                    "cade",
                    "thistle",
                    "elder berry",
                    "seed",
                    "joy",
                    "pine",
                    "elusive",
                    "raspberry",
                    "hazel",
                    "hat",
                    "oat",
                    "millet",
                    "cloudberry",
                    "club",
                    "clover",
                    "tuber",
                    "choke",
                    "coriander",
                    "barley",
                    "cone",
                    "cone",
                    "gooseberry",
                    "spice",
                    "cumin",
                    "cabbage",
                    "chervil",
                    "lichen",
                    "lily",
                    "flax",
                    "lingon",
                    "onion",
                    "leaf",
                    "melisma",
                    "carrot",
                    "moss",
                    "morel",
                    "mint",
                    "orache",
                    "straw",
                    "nate",
                    "nettle",
                    "pepper",
                    "pear",
                    "rhubarb",
                    "rain",
                    "root",
                    "rye",
                    "rake",
                    "radish",
                    "salad",
                    "anemone",
                    "stalk",
                    "gleam",
                    "agaric",
                    "cocklebur",
                    "beauty",
                    "sloe",
                    "strawberry",
                    "thicket",
                    "bovinus",
                    "spur",
                    "sting",
                    "star",
                    "storm",
                    "fungus",
                    "thyme",
                    "thorn",
                    "truffle",
                    "tongue",
                    "tuft",
                    "wool",
                    "poppy",
                    "reed",
                    "wheat",
                    "willow",
                    "viva",
                    "weave",
                    "pea",
                    "herb"
                ]
            },
            "relic": {
                "prefix": [
                   "NEED HELP"
                ],
                "suffix": [
                    "WITH THESE!"
                ]
            },
            "weapon": {
                "prefix": [
                    "bear",
                    "leaf",
                    "blood",
                    "drake",
                    "dragon",
                    "dwarf",
                    "fire",
                    "gave",
                    "grim",
                    "grey",
                    "witch",
                    "leech",
                    "jarl",
                    "earth",
                    "jorn",
                    "jotun",
                    "giant",
                    "copper",
                    "raven",
                    "mist",
                    "mirk",
                    "dark",
                    "moon",
                    "night",
                    "rafner",
                    "rose",
                    "red",
                    "silver",
                    "snow",
                    "sun",
                    "stone",
                    "star",
                    "storme",
                    "black",
                    "thorn",
                    "thistle",
                    "troll",
                    "wolf",
                    "winter",
                    "vitner",
                    "goblin",
                    "ash"
                ],
                "suffix": [
                    "sting",
                    "star",
                    "quencher",
                    "thirster",
                    "storm",
                    "thorn",
                    "tongue",
                    "light",
                    "rod",
                    "eater",
                    "slayer",
                    "crusher",
                    "slash",
                    "bane",
                    "blade",
                    "edge",
                    "bite",
                    "needle",
                    "devourer",
                    "gorger",
                    "butcher",
                    "sever",
                    "slicer",
                    "carver",
                    "gasher",
                    "chopper",
                    "ripper",
                    "blight",
                    "knife",
                    "sword",
                    "destroyer"
                ],
                "alone": [
                    "misery",
                    "despair",
                    "dawn",
                    "covergence",
                    "conqueror",
                    "frost",
                    "riddle",
                    "midnight",
                    "defender",
                    "scar",
                    "verdict",
                    "hope",
                    "fall",
                    "justice",
                    "gift",
                    "lament",
                    "nightmare",
                    "shadow",
                    "savage"
                ]
            },
            "ale": {
                "prefix": [
                    "evening",
                    "fairy",
                    "bear",
                    "blood",
                    "bloody",
                    "bronze",
                    "dragon",
                    "dwarf",
                    "fire",
                    "gave",
                    "grim",
                    "gilded",
                    "earth",
                    "mountain",
                    "jorn",
                    "jotun",
                    "raven",
                    "moon",
                    "ox",
                    "rose",
                    "red",
                    "sharp",
                    "sun",
                    "stone",
                    "star",
                    "storme",
                    "troll",
                    "winter",
                    "spring",
                    "people",
                    "people",
                    "people",
                    "people",
                    "people",
                    "people",
                    "people",
                    "people",
                    "people",
                    "people",
                    "people",
                    "people",
                    "people"
                ],
                "suffix": [
                    "ale",
                    "beer",
                    "old brew",
                    "mead",
                    "stout",
                    "malt",
                    "lager"
                ]
            },
            "ship": {
                "prefix": [
                    "evening",
                    "bear",
                    "blood",
                    "bloody",
                    "dragon",
                    "gave",
                    "grim",
                    "grey",
                    "gilded",
                    "heavenly",
                    "copper",
                    "raven",
                    "moon",
                    "night",
                    "arrow",
                    "rose",
                    "red",
                    "silver",
                    "sun",
                    "star",
                    "storme",
                    "winter",
                    "white",
                    "river",
                    "death's",
                    "nail",
                    "meadow",
                    "meadow",
                    "meadow",
                    "meadow",
                ],
                "suffix": [
                   "eagle",
                   "fish",
                   "plunderer",
                   "ship",
                   "knarr",
                   "longship",
                   "fjord",
                   "basket",
                   "snekkja",
                   "ferja"
                ],
                "alone": [
                    "swan",
                    "bear",
                    "hawk",
                    "greygoose",
                    "gryphon",
                    "ox",
                    "long serpent",
                    "dragon",
                    "dreki",
                    "cow of the fjord",
                    "woodbag"
                ]
            },
            "horse": {
                "prefix": [
                    "gift of the",
                    "moon",
                    "night",
                    "arrow",
                    "silver",
                    "sun",
                    "star",
                    "lightning"
                ],
                "suffix": [
                   "elves",
                   "eagle",
                   "sword",
                   "axe",
                   "leaf",
                   "eagle",
                   "fate",
                   "fire",
                   "hawk",
                   "bliss"
                ],
                "alone": [
                    "wind",
                    "hawk",
                    "gryphon",
                    "dragon",
                    "swan",
                    "happiness",
                    "lightning",
                    "banner",
                    "blossom"
                ]
            }
        }
    },
    "sv": {
        "nameSpacer": "",
        "people": {
            "mittlander": {
                "prefix": [
                    "bren",
                    "bran",
                    "edel",
                    "edil",
                    "eid",
                    "eo",
                    "gul",
                    "gal",
                    "guld",
                    "gul",
                    "hedel",
                    "her",
                    "log",
                    "mau",
                    "maug",
                    "mor",
                    "mord"
                ],
                "suffix": {
                    "male": [
                        "ard",
                        "bard",
                        "jar",
                        "gjar",
                        "ed",
                        "hed",
                        "finn",
                        "fraidh",
                        "han",
                        "marr",
                        "red",
                        "rik",
                        "win",
                        "winn"
                    ],
                    "female": [
                        "non",
                        "annon",
                        "de",
                        "elde",
                        "eid",
                        "heid",
                        "trude",
                        "itrude",
                        "frid",
                        "lynn",
                        "na",
                        "nhja",
                        "rynn",
                        "wa",
                        "wen"
                    ]
                },
                "lastnames": {
                    "family": [
                        "swaahndril",
                        "culihan",
                        "gunnrahóel",
                        "navor'na",
                        "gwendan",
                        "luwndhinn",
                        "lehwgrhein",
                        "wallhin"
                    ],
                    "epithets": [
                        "ormdräpe",
                        "trollhacke",
                        "vindryttare"
                    ],
                    "profession": [
                        "smed",
                        "bonde",
                        "uppfödare",
                        "skogshuggare"
                    ],
                    "nickname": [
                        "klåfinger",
                        "snenäsa",
                        "harläpp",
                        "trollöga"
                    ]
                }
            },
            "stormlander": {
                "prefix": [
                    "as",
                    "bod",
                    "bryn",
                    "hall",
                    "hraf",
                    "ing",
                    "jor",
                    "tor",
                    "vig",
                    "vret"
                ],
                "suffix": {
                    "male": [
                        "biorn",
                        "geir",
                        "grim",
                        "galt",
                        "jald",
                        "orm",
                        "ulf",
                        "ur",
                        "vald",
                        "varr"
                    ],
                    "female": [
                        "a",
                        "dis",
                        "dott",
                        "gerd",
                        "hild",
                        "umbla",
                        "unn",
                        "veig",
                        "vida",
                        "vigg"
                    ]
                },
                "lastnames": {
                    "epithets": [
                        "gaveslaktare",
                        "trollhacke",
                        "blodspridare"
                    ],
                    "profession": [
                        "smed",
                        "bonde",
                        "båtbyggare",
                        "skogshuggare"
                    ],
                    "nickname": [
                        "klåfinger",
                        "snenäsa",
                        "harläpp",
                        "trollöga"
                    ]
                }
            },
            "virann": {
                "prefix": [
                    "ber",
                    "beor",
                    "bur",
                    "buor",
                    "bewr",
                    "bewor",
                    "brun",
                    "bruni",
                    "bran",
                    "brani",
                    "bron",
                    "broni",
                    "donni",
                    "dunni",
                    "ed",
                    "edel",
                    "ev",
                    "evel",
                    "fri",
                    "fride",
                    "fra",
                    "frade",
                    "fru",
                    "frude",
                    "gal",
                    "gals",
                    "gol",
                    "gols",
                    "hun",
                    "huni",
                    "hen",
                    "heni",
                    "klod",
                    "klodi",
                    "klud",
                    "kludi",
                    "mer",
                    "mero",
                    "mor",
                    "moro",
                    "ro",
                    "rode",
                    "ru",
                    "rude",
                    "sor",
                    "sork",
                    "sar",
                    "sark",
                    "sul",
                    "suli",
                    "sol",
                    "soli",
                    "sal",
                    "sali",
                    "tryn",
                    "tryni",
                    "tron",
                    "troni"
                ],
                "suffix": {
                    "male": [
                        "bad",
                        "gar",
                        "gist",
                        "kar",
                        "kind",
                        "kull",
                        "pis",
                        "red",
                        "rik",
                        "till",
                        "thill",
                        "walan",
                        "vard",
                        "wig",
                        "vik"
                    ],
                    "female": [
                        "th",
                        "dith",
                        "fing",
                        "gond",
                        "hed",
                        "hedd",
                        "kild",
                        "len",
                        "mynt",
                        "mynta",
                        "nell",
                        "sta",
                        "stai",
                        "strid",
                        "thne",
                        "tilde",
                        "winda"
                    ]
                },
                "lastnames": {
                    "family": ["inget familje namn"],
                    "epithets": [
                        "vitnerdräpe",
                        "trollhacke",
                        "stormekrossare"
                    ],
                    "profession": [
                        "smed",
                        "bonde",
                        "uppfödare",
                        "skogshuggare"
                    ],
                    "nickname": [
                        "klåfinger",
                        "snenäsa",
                        "harläpp",
                        "trollöga"
                    ]
                }
            },
            "wildfolk": {
                "prefix": [],
                "suffix": {
                    "male": [],
                    "female": []
                }
            },
            "elf": {
                "prefix": [
                    "harp",
                    "jep",
                    "jeppi",
                    "kyll",
                    "lep",
                    "lepo",
                    "norma",
                    "normo",
                    "pojh",
                    "pojha",
                    "sirp",
                    "sirpa",
                    "syll",
                    "vaj",
                    "vajne",
                    "val",
                    "vali"
                ],
                "suffix": {
                    "male": [
                        "hang",
                        "ehang",
                        "iaho",
                        "piaho",
                        "akka",
                        "ingas",
                        "jias",
                        "lainen",
                        "mojna",
                        "pihi",
                        "taja",
                        "ua"
                    ],
                    "female": [
                        "ala",
                        "pala",
                        "atta",
                        "hiska",
                        "ika",
                        "iulu",
                        "iullu",
                        "kosva",
                        "lajna",
                        "likki",
                        "olvi",
                        "sinka"
                    ]
                }
            },
            "dwarf": {
                "prefix": [
                    "bor",
                    "brok",
                    "dvor",
                    "fifun",
                    "glo",
                    "gly",
                    "jo",
                    "jor",
                    "niful",
                    "ru",
                    "ruk",
                    "tjeb",
                    "tor",
                    "zvor"
                ],
                "suffix": {
                    "male": [
                        "olgd",
                        "dolga",
                        "ka",
                        "kka",
                        "ust",
                        "rust",
                        "drank",
                        "gel",
                        "linkk",
                        "logi",
                        "rovv",
                        "van",
                        "var",
                        "zink"
                    ]
                }
            },
            "troll": {
                "prefix": [
                    "a",
                    "nak",
                    "gnak",
                    "vårt",
                    "vårta",
                    "årt",
                    "dy",
                    "dry",
                    "dryg",
                    "e",
                    "fis",
                    "fisk",
                    "ful",
                    "full",
                    "furm",
                    "gri",
                    "grik",
                    "grinn",
                    "gris",
                    "hog",
                    "ke",
                    "klo",
                    "knorr",
                    "lill",
                    "knott"
                ],
                "suffix": [
                    "lork",
                    "lorsk",
                    "lus",
                    "mo",
                    "must",
                    "ogg",
                    "päls",
                    "ryt",
                    "sno",
                    "snor",
                    "snus",
                    "stink",
                    "sto",
                    "stor",
                    "tande",
                    "tide",
                    "tov",
                    "urg",
                    "vis",
                    "yge",
                    "ygel",
                    "yt"
                ]
            }
        },
        "town": {
            "prefix": [
                "al",
                "alfe",
                "aske",
                "atla",
                "aud",
                "audur",
                "bjalfe",
                "bjorn",
                "björk",
                "blid",
                "blot",
                "bock",
                "borke",
                "brage",
                "brase",
                "bronja",
                "bål",
                "egil",
                "ejlög",
                "ek",
                "ese",
                "fager",
                "falk",
                "frost",
                "gad",
                "galt",
                "gaute",
                "gerd",
                "gisle",
                "gno",
                "gorm",
                "grim",
                "grise",
                "gruve",
                "grå",
                "gyda",
                "hamra",
                "helga",
                "hella",
                "hrim",
                "häll",
                "jon",
                "jorna",
                "jot",
                "järn",
                "jökull",
                "jöt",
                "kal",
                "kjöle",
                "koppar",
                "korp",
                "kråk",
                "kviste",
                "laupe",
                "lille",
                "lo",
                "lov",
                "marsk",
                "mjöd",
                "mull",
                "möln",
                "nid",
                "njal",
                "odd",
                "orm",
                "ost",
                "oster",
                "rafner",
                "rauk",
                "run",
                "ränne",
                "silver",
                "skuru",
                "smed",
                "sol",
                "sot",
                "starke",
                "sten",
                "stig",
                "stor",
                "storm",
                "sund",
                "tall",
                "tindra",
                "troll",
                "tur",
                "ulf",
                "ulm",
                "unn",
                "vide",
                "vild",
                "vinter",
                "vis",
                "vit",
                "vret",
                "väster",
                "åker",
                "ås",
                "älg",
                "öst"
            ],
            "suffix": [
                "al",
                "anger",
                "backa ",
                "berg ",
                "blot",
                "bod ",
                "boda ",
                "borg",
                "botten",
                "brant",
                "bro ",
                "bruk ",
                "brunn ",
                "by ",
                "bäck ",
                "dal",
                "dis ",
                "ed",
                "fjord ",
                "fjäll ",
                "fors",
                "fors ",
                "frost ",
                "fält",
                "gang",
                "gap ",
                "gard ",
                "gull",
                "gård ",
                "haga ",
                "hall",
                "hammar ",
                "hamn ",
                "harg ",
                "hed",
                "hem",
                "holm ",
                "holt ",
                "hult",
                "häll",
                "hög ",
                "inge ",
                "klint",
                "klippan ",
                "kulla ",
                "kvarn",
                "källa ",
                "köping",
                "lev ",
                "lid ",
                "ljung ",
                "lund ",
                "lycke ",
                "löse ",
                "löv ",
                "mark ",
                "mosse",
                "mönja ",
                "nejd",
                "näs ",
                "om",
                "pass",
                "ro",
                "rum ",
                "rup ",
                "ryd ",
                "rödja ",
                "sala ",
                "skog ",
                "slaga ",
                "sorg ",
                "sta",
                "stein",
                "stena ",
                "stig",
                "stock ",
                "sund",
                "tegn ",
                "ting",
                "tjärn ",
                "tofta ",
                "topp",
                "torp ",
                "träsk ",
                "tun",
                "tune ",
                "um ",
                "vad",
                "vall",
                "vi ",
                "vik",
                "vind ",
                "virja ",
                "vy ",
                "å",
                "åker ",
                "åkra ",
                "ås ",
                "älv",
                "äng"
            ]
        },
        "tavern": {
            "prefix": [
                "troll",
                "röt",
                "orm",
                "hugg",
                "skald",
                "svin",
                "rövar",
                "mjöd",
                "hjälte",
                "korp",
                "stormes",
                "bronje",
                "tråg",
                "skogs",
                "öl",
                "mjöd",
                "tvilling",
                "härjar",
                "garm",
                "svultna",
                "lytte",
                "trasiga",
                "stegrande",
                "frusna",
                "bäcka",
                "gave",
                "saga",
                "skägg",
                "moss",
                "lav",
                "fjäll",
                "barr",
                "drak",
                "möra",
                "skummande",
                "galna",
                "uppretade",
                "slaktade",
                "lagade",
                "blå",
                "röda",
                "gröna",
                "gula",
                "vita",
                "svarta",
                "bruna",
                "försupne"
            ],
            "suffix": [
                "hallen",
                "grytet",
                "hålan",
                "stian",
                "krogen",
                "syltan",
                "svinet",
                "björnen",
                "stugan",
                "huset",
                "hålet",
                "vaken",
                "viken",
                "tjärn",
                "torp",
                "fjäll",
                "huvudet",
                "tornet",
                "korsning",
                "korsningen",
                "riket",
                "platsen",
                "punkten",
                "galten",
                "vandraren",
                "ponnyn",
                "bocken",
                "kaninen",
                "stopet",
                "hålet",
                "vaken",
                "viken",
                "tjärn",
                "torp",
                "huvudet",
                "hus",
                "katten",
                "ormen",
                "skräddaren"
            ]
        },
        "plant": {
            "prefix": [
                "afton",
                "alva",
                "bergs",
                "bjark",
                "björn",
                "blad",
                "blod",
                "blods",
                "brons",
                "dagg",
                "dis",
                "drak",
                "dvärg",
                "dy",
                "eld",
                "fackel",
                "fager",
                "finger",
                "garna",
                "gave",
                "grim",
                "grå",
                "gråe",
                "gul",
                "gull",
                "har",
                "hingst",
                "himla",
                "hird",
                "hjort",
                "humle",
                "hväle",
                "häst",
                "häx",
                "igel",
                "jarla",
                "jord",
                "jorn",
                "jotun",
                "järn",
                "jätte",
                "kalder",
                "knytt",
                "kol",
                "koppar",
                "korp",
                "kungs",
                "kärr",
                "lom",
                "lund",
                "mal",
                "manna",
                "marsk",
                "mist",
                "mork",
                "mörk",
                "myr",
                "mån",
                "natt",
                "nät",
                "orm",
                "ox",
                "pil",
                "puder",
                "rafner",
                "ros",
                "röd",
                "silver",
                "sjö",
                "skarp",
                "skav",
                "skogs",
                "skvätt",
                "snö",
                "sol",
                "sten",
                "stjärn",
                "stjärne",
                "storme",
                "svart",
                "svin",
                "tagg",
                "talg",
                "tistel",
                "tok",
                "troll",
                "tråd",
                "törn",
                "vall",
                "varg",
                "vatten",
                "vild",
                "vinter",
                "vit",
                "vitner",
                "vår",
                "vätte",
                "älg",
                "älv",
                "älva",
                "älve",
                "äng",
                "änga",
                "ängs"
            ],
            "suffix": [
                "anis",
                "apel",
                "ax",
                "bark",
                "beta",
                "bjärt",
                "blad",
                "blom",
                "blomster",
                "bräken",
                "buske",
                "bär",
                "böna",
                "cikoria",
                "dill",
                "ek",
                "en",
                "fibbla",
                "fläder",
                "frö",
                "glädje",
                "gran",
                "gäck",
                "hallon",
                "hassel",
                "hatt",
                "havre",
                "hirs",
                "hjortron",
                "klubba",
                "klöver",
                "knöl",
                "kocka",
                "koriander",
                "korn",
                "kott",
                "kotte",
                "krusbär",
                "krydda",
                "kummin",
                "kål",
                "körvel",
                "lav",
                "lilja",
                "lin",
                "lingon",
                "lök",
                "löv",
                "meliss",
                "morot",
                "mossa",
                "murkla",
                "mynta",
                "målla",
                "måra",
                "nate",
                "nässla",
                "peppar",
                "päron",
                "rabarber",
                "regn",
                "ris",
                "rot",
                "råg",
                "räfsa",
                "rättika",
                "sallad",
                "sippa",
                "själke",
                "skatta",
                "skimra",
                "skivling",
                "skräppa",
                "sköna",
                "slån",
                "smultron",
                "snår",
                "sopp",
                "sporre",
                "starr",
                "sticka",
                "stjärna",
                "storm",
                "svamp",
                "timjan",
                "torn",
                "tryffel",
                "tunga",
                "tuva",
                "törn",
                "törne",
                "ull",
                "vallmo",
                "vass",
                "vete",
                "vide",
                "viva",
                "väv",
                "ärt",
                "ärtskocka",
                "ört"
            ]
        }
    },
    "es": {
    
    },
    "fr": {
    
    }

};