window.nameData = {
    "en": {
        "people": {
            "mittlander": {
                "prefix": [
                    "Bren",
                    "Bran",
                    "Edel",
                    "Edil",
                    "Eid",
                    "Eo",
                    "Gul",
                    "Gal",
                    "Guld",
                    "Gul",
                    "Hedel",
                    "Her",
                    "Log",
                    "Mau",
                    "Maug",
                    "Mor",
                    "Mord"
                ],
                "suffix": {
                    "male": [
                        "ard",
                        "bard",
                        "jar",
                        "gjar",
                        "ed",
                        "hed",
                        "finn",
                        "fraidh",
                        "han",
                        "marr",
                        "red",
                        "rik",
                        "win",
                        "winn"
                    ],
                    "female": [
                        "non",
                        "annon",
                        "de",
                        "elde",
                        "eid",
                        "heid",
                        "trude",
                        "itrude",
                        "frid",
                        "lynn",
                        "na",
                        "nhja",
                        "rynn",
                        "wa",
                        "wen"
                    ]
                },
                "lastnames": {
                    "family": [
                        "Swaahndril",
                        "Culihan",
                        "Gunnrahóel",
                        "Navor'Na",
                        "Gwendan",
                        "Luwndhinn",
                        "Lehwgrhein",
                        "Wallhin"
                    ],
                    "epithets": [
                        "Wyrmslayer",
                        "Trollchopper",
                        "Windrider"
                    ],
                    "profession": [
                        "Smith",
                        "Farmer",
                        "Breeder",
                        "Logger"
                    ],
                    "nickname": [
                        "Tamper",
                        "Askew nose",
                        "Harelip",
                        "Trolleye"
                    ]
                }
            },
            "stormlander": {
                "prefix": [
                    "as",
                    "bod",
                    "bryn",
                    "hall",
                    "hraf",
                    "ing",
                    "jor",
                    "tor",
                    "vig",
                    "vret"
                ],
                "suffix": {
                    "male": [
                        "biorn",
                        "geir",
                        "grim",
                        "galt",
                        "jald",
                        "orm",
                        "ulf",
                        "ur",
                        "vald",
                        "varr"
                    ],
                    "female": [
                        "a",
                        "dis",
                        "dott",
                        "gerd",
                        "hild",
                        "umbla",
                        "unn",
                        "veig",
                        "vida",
                        "vigg"
                    ]
                },
                "lastnames": {
                    "epithets": [
                        "Nidslayer",
                        "Trollchopper",
                        "Bloodspreader"
                    ],
                    "profession": [
                        "Smith",
                        "Farmer",
                        "Boatbuilder",
                        "Logger"
                    ],
                    "nickname": [
                        "Tamper",
                        "Askew nose",
                        "Harelip",
                        "Trolleye"
                    ]
                }
            },
            "virann": {
                "prefix": [
                    "Ber",
                    "Beor",
                    "Bur",
                    "Buor",
                    "Bewr",
                    "Bewor",
                    "Brun",
                    "Bruni",
                    "Bran",
                    "Brani",
                    "Bron",
                    "Broni",
                    "Donni",
                    "Dunni",
                    "Ed",
                    "Edel",
                    "Ev",
                    "Evel",
                    "Fri",
                    "Fride",
                    "Fra",
                    "Frade",
                    "Fru",
                    "Frude",
                    "Gal",
                    "Gals",
                    "Gol",
                    "Gols",
                    "Hun",
                    "Huni",
                    "Hen",
                    "Heni",
                    "Klod",
                    "Klodi",
                    "Klud",
                    "Kludi",
                    "Mer",
                    "Mero",
                    "Mor",
                    "Moro",
                    "Ro",
                    "Rode",
                    "Ru",
                    "Rude",
                    "Sor",
                    "Sork",
                    "Sar",
                    "Sark",
                    "Sul",
                    "Suli",
                    "Sol",
                    "Soli",
                    "Sal",
                    "Sali",
                    "Tryn",
                    "Tryni",
                    "Tron",
                    "Troni"
                ],
                "suffix": {
                    "male": [
                        "bad",
                        "gar",
                        "gist",
                        "kar",
                        "kind",
                        "kull",
                        "pis",
                        "red",
                        "rik",
                        "till",
                        "thill",
                        "walan",
                        "vard",
                        "wig",
                        "vik"
                    ],
                    "female": [
                        "th",
                        "dith",
                        "fing",
                        "gond",
                        "hed",
                        "hedd",
                        "kild",
                        "len",
                        "mynt",
                        "mynta",
                        "nell",
                        "sta",
                        "stai",
                        "strid",
                        "thne",
                        "tilde",
                        "winda"
                    ]
                },
                "lastnames": {
                    "family": ["NO FAMILY NAMES IN LIST"],
                    "epithets": [
                        "Magekiller",
                        "Trollchopper",
                        "Heathencrusher"
                    ],
                    "profession": [
                        "Smith",
                        "Farmer",
                        "Breeder",
                        "Logger"
                    ],
                    "nickname": [
                        "Tamper",
                        "Askew nose",
                        "Harelip",
                        "Trolleye"
                    ]
                }
            },
            "wildfolk": {
                "prefix": [],
                "suffix": {
                    "male": [],
                    "female": []
                }
            },
            "elf": {
                "prefix": [
                    "Harp",
                    "Jep",
                    "Jeppi",
                    "Kyll",
                    "Lep",
                    "Lepo",
                    "Norma",
                    "Normo",
                    "Pojh",
                    "Pojha",
                    "Sirp",
                    "Sirpa",
                    "Syll",
                    "Vaj",
                    "Vajne",
                    "Val",
                    "Vali"
                ],
                "suffix": {
                    "male": [
                        "hang",
                        "ehang",
                        "iaho",
                        "piaho",
                        "akka",
                        "ingas",
                        "jias",
                        "lainen",
                        "mojna",
                        "pihi",
                        "taja",
                        "ua"
                    ],
                    "female": [
                        "ala",
                        "pala",
                        "atta",
                        "hiska",
                        "ika",
                        "iulu",
                        "iullu",
                        "kosva",
                        "lajna",
                        "likki",
                        "olvi",
                        "sinka"
                    ]
                }
            },
            "dwarf": {
                "prefix": [
                    "Bor",
                    "Brok",
                    "Dvor",
                    "Fifun",
                    "Glo",
                    "Gly",
                    "Jo",
                    "Jor",
                    "Niful",
                    "Ru",
                    "Ruk",
                    "Tjeb",
                    "Tor",
                    "Zvor"
                ],
                "suffix": {
                    "male": [
                        "olgd",
                        "dolga",
                        "ka",
                        "kka",
                        "ust",
                        "rust",
                        "drank",
                        "gel",
                        "linkk",
                        "logi",
                        "rovv",
                        "van",
                        "var",
                        "zink"
                    ]
                }
            },
            "troll": {
                "prefix": [
                    "a",
                    "nak",
                    "gnak",
                    "wart",
                    "wort",
                    "ort",
                    "sludge",
                    "lou",
                    "loud",
                    "e",
                    "fart",
                    "fish",
                    "foul",
                    "grog",
                    "furm",
                    "gri",
                    "grik",
                    "grinn",
                    "pig",
                    "hog",
                    "ke",
                    "claw",
                    "curl",
                    "wee",
                    "gnat"
                ],
                "suffix": [
                    "lork",
                    "lorsk",
                    "louse",
                    "mo",
                    "must",
                    "sapp",
                    "ogg",
                    "fur",
                    "roar",
                    "reak",
                    "snitch",
                    "poach",
                    "snuff",
                    "stink",
                    "mare",
                    "fa",
                    "fat",
                    "teet",
                    "teeth",
                    "tide",
                    "tangle",
                    "snarl",
                    "urg",
                    "wise",
                    "yge",
                    "ygel",
                    "yt"
                ]
            }
        },
        "town": {
            "prefix": [
                "alder",
                "elf",
                "ash",
                "atla",
                "aud",
                "audur",
                "bjalfe",
                "bjorn",
                "birch",
                "placid",
                "blut",
                "buck",
                "borke",
                "brage",
                "brase",
                "bronja",
                "bale",
                "egil",
                "ejlög",
                "oak",
                "ese",
                "fair",
                "falcon",
                "frost",
                "gad",
                "boar",
                "gaute",
                "gerd",
                "gisle",
                "toil",
                "gorm",
                "grim",
                "pig",
                "mine",
                "grey",
                "gyda",
                "hammer",
                "sanctify",
                "hall",
                "hrim",
                "hall",
                "jon",
                "jorna",
                "jot",
                "iron",
                "jökull",
                "jöt",
                "bleak",
                "kjole",
                "copper",
                "raven",
                "raven",
                "twig",
                "laupe",
                "small",
                "lynx",
                "laud",
                "marsk",
                "mead",
                "earth",
                "cloud",
                "nid",
                "njal",
                "odd",
                "snake",
                "east",
                "oster",
                "rafner",
                "rauk",
                "runic",
                "silver",
                "scour",
                "smith",
                "sun",
                "soot",
                "stron",
                "stone",
                "path",
                "great",
                "storm",
                "strait",
                "pine",
                "twinkle",
                "troll",
                "luck",
                "ulf",
                "ulm",
                "unn",
                "willow",
                "wild",
                "winter",
                "wise",
                "vhite",
                "vret",
                "west",
                "field",
                "ridge",
                "moose",
                "east"
            ],
            "suffix": [
                "alder",
                "anger",
                "back",
                "mount",
                "blut",
                "shed",
                "sheddy",
                "castle",
                "bottom",
                "steep",
                "bridge",
                "mill",
                "well",
                "village",
                "brook",
                "valley",
                "haze",
                "oath",
                "fjord",
                "mountain",
                "rapids",
                "frost",
                "field",
                "gang",
                "mouth",
                "gard",
                "gold",
                "farm",
                "haga",
                "hall",
                "hammer",
                "port",
                "harg",
                "heath",
                "home",
                "holm",
                "holt",
                "hult",
                "hall",
                "high",
                "lodge",
                "rock",
                "cliff",
                "hill",
                "mill",
                "spring",
                "market",
                "live",
                "lid",
                "ling",
                "grove",
                "luck",
                "leaf",
                "ground",
                "bog",
                "monje",
                "clime",
                "isthmus",
                "om",
                "pass",
                "row",
                "room",
                "rup",
                "ryd",
                "grubbed",
                "sala",
                "woods",
                "forest",
                "sorrow",
                "sta",
                "stein",
                "stone",
                "way",
                "log",
                "strait",
                "tegn",
                "thing",
                "tarn",
                "thwart",
                "top",
                "croft",
                "swamp",
                "tun",
                "tune",
                "um",
                "calf",
                "ley",
                "vi",
                "bay",
                "wind",
                "virja",
                "view",
                "field",
                "ridge",
                "river",
                "meadow"
            ]
        },
        "tavern": {
            "prefix": [
                "troll",
                "rot",
                "snake",
                "hugg",
                "skald",
                "pig",
                "robber",
                "mead",
                "hero",
                "raven",
                "storme's",
                "bronje",
                "trough",
                "forest",
                "ale",
                "twin",
                "ravage",
                "garm",
                "starving",
                "listening",
                "broken",
                "prancing",
                "frozen",
                "brook",
                "gave",
                "saga",
                "beard",
                "moss",
                "lichen",
                "mountain",
                "fir needle",
                "dragon",
                "tender",
                "frothy",
                "crazy",
                "enraged",
                "slaughtered",
                "fried",
                "cooked",
                "red",
                "green",
                "yellow",
                "white",
                "black",
                "brown",
                "drunken"
            ],
            "suffix": [
                "hall",
                "burrow",
                "den",
                "sty",
                "tavern",
                "hash house",
                "pig",
                "bear",
                "cottage",
                "home",
                "hole",
                "ice hole",
                "gulf",
                "tarn",
                "croft",
                "mountain",
                "head",
                "tower",
                "crossing",
                "realm",
                "place",
                "point",
                "boar",
                "wanderer",
                "ponny",
                "buck",
                "rabbit",
                "pint",
                "head",
                "house",
                "cat",
                "snake",
                "tailor"
            ]
        },
        "plant": {
            "prefix": [
                "evening",
                "fairy",
                "mountainous",
                "bjark",
                "bear",
                "leaf",
                "blood",
                "bloody",
                "bronze",
                "dew",
                "dis",
                "drake",
                "dwarf",
                "mire",
                "fire",
                "torch",
                "fare",
                "finger",
                "yarn",
                "gave",
                "grim",
                "grey",
                "grey",
                "yellow",
                "gilded",
                "hare",
                "stallion",
                "heavenly",
                "hird",
                "deer",
                "hop",
                "hvale",
                "autumn",
                "fall",
                "witch",
                "leech",
                "jarl",
                "earth",
                "jorn",
                "jotun",
                "iron",
                "giant",
                "calder",
                "toffle",
                "coal",
                "copper",
                "raven",
                "king's",
                "marsh",
                "fen",
                "loon",
                "grove",
                "moth",
                "manna",
                "constable",
                "mist",
                "mirk",
                "dark",
                "mire",
                "moon",
                "night",
                "nut",
                "snake",
                "ox",
                "arrow",
                "powder",
                "rafner",
                "rose",
                "red",
                "silver",
                "lake",
                "sharp",
                "scuff",
                "forestry",
                "drop",
                "snow",
                "sun",
                "stone",
                "star",
                "storme",
                "black",
                "swine",
                "thorn",
                "tallow",
                "thistle",
                "fool",
                "troll",
                "tree",
                "mound",
                "wolf",
                "water",
                "wild",
                "winter",
                "white",
                "vitner",
                "spring",
                "goblin",
                "elk",
                "river",
                "fairy",
                "fay",
                "lea",
                "field",
                "meadow"
            ],
            "suffix": [
                "anise",
                "apple",
                "spike",
                "bark",
                "beet",
                "brightly",
                "leaf",
                "bloom",
                "flower",
                "bracken",
                "bush",
                "berry",
                "bean",
                "chicory",
                "dill",
                "oak",
                "cade",
                "thistle",
                "elder berry",
                "seed",
                "joy",
                "pine",
                "elusive",
                "raspberry",
                "hazel",
                "hat",
                "oat",
                "millet",
                "cloudberry",
                "club",
                "clover",
                "tuber",
                "choke",
                "coriander",
                "barley",
                "cone",
                "cone",
                "gooseberry",
                "spice",
                "cumin",
                "cabbage",
                "chervil",
                "lichen",
                "lily",
                "flax",
                "lingon",
                "onion",
                "leaf",
                "melisma",
                "carrot",
                "moss",
                "morel",
                "mint",
                "orache",
                "straw",
                "nate",
                "nettle",
                "pepper",
                "pear",
                "rhubarb",
                "rain",
                "root",
                "rye",
                "rake",
                "radish",
                "salad",
                "anemone",
                "stalk",
                "gleam",
                "agaric",
                "cocklebur",
                "beauty",
                "sloe",
                "strawberry",
                "thicket",
                "bovinus",
                "spur",
                "sting",
                "star",
                "storm",
                "fungus",
                "thyme",
                "thorn",
                "truffle",
                "tongue",
                "tuft",
                "wool",
                "poppy",
                "reed",
                "wheat",
                "willow",
                "viva",
                "weave",
                "pea",
                "herb"
            ]
        }
    },
    "sv": {
        "people": {
            "mittlander": {
                "prefix": [
                    "Bren",
                    "Bran",
                    "Edel",
                    "Edil",
                    "Eid",
                    "Eo",
                    "Gul",
                    "Gal",
                    "Guld",
                    "Gul",
                    "Hedel",
                    "Her",
                    "Log",
                    "Mau",
                    "Maug",
                    "Mor",
                    "Mord"
                ],
                "suffix": {
                    "male": [
                        "ard",
                        "bard",
                        "jar",
                        "gjar",
                        "ed",
                        "hed",
                        "finn",
                        "fraidh",
                        "han",
                        "marr",
                        "red",
                        "rik",
                        "win",
                        "winn"
                    ],
                    "female": [
                        "non",
                        "annon",
                        "de",
                        "elde",
                        "eid",
                        "heid",
                        "trude",
                        "itrude",
                        "frid",
                        "lynn",
                        "na",
                        "nhja",
                        "rynn",
                        "wa",
                        "wen"
                    ]
                },
                "lastnames": {
                    "family": [
                        "Swaahndril",
                        "Culihan",
                        "Gunnrahóel",
                        "Navor'Na",
                        "Gwendan",
                        "Luwndhinn",
                        "Lehwgrhein",
                        "Wallhin"
                    ],
                    "epithets": [
                        "Ormdräpe",
                        "Trollhacke",
                        "Vindryttare"
                    ],
                    "profession": [
                        "Smed",
                        "Bonde",
                        "Uppfödare",
                        "Skogshuggare"
                    ],
                    "nickname": [
                        "Klåfinger",
                        "Snenäsa",
                        "Harläpp",
                        "Trollöga"
                    ]
                }
            },
            "stormlander": {
                "prefix": [
                    "as",
                    "bod",
                    "bryn",
                    "hall",
                    "hraf",
                    "ing",
                    "jor",
                    "tor",
                    "vig",
                    "vret"
                ],
                "suffix": {
                    "male": [
                        "biorn",
                        "geir",
                        "grim",
                        "galt",
                        "jald",
                        "orm",
                        "ulf",
                        "ur",
                        "vald",
                        "varr"
                    ],
                    "female": [
                        "a",
                        "dis",
                        "dott",
                        "gerd",
                        "hild",
                        "umbla",
                        "unn",
                        "veig",
                        "vida",
                        "vigg"
                    ]
                },
                "lastnames": {
                    "epithets": [
                        "Gaveslaktare",
                        "Trollhacke",
                        "Blodspridare"
                    ],
                    "profession": [
                        "Smed",
                        "Bonde",
                        "Båtbyggare",
                        "Skogshuggare"
                    ],
                    "nickname": [
                        "Klåfinger",
                        "Snenäsa",
                        "Harläpp",
                        "Trollöga"
                    ]
                }
            },
            "virann": {
                "prefix": [
                    "Ber",
                    "Beor",
                    "Bur",
                    "Buor",
                    "Bewr",
                    "Bewor",
                    "Brun",
                    "Bruni",
                    "Bran",
                    "Brani",
                    "Bron",
                    "Broni",
                    "Donni",
                    "Dunni",
                    "Ed",
                    "Edel",
                    "Ev",
                    "Evel",
                    "Fri",
                    "Fride",
                    "Fra",
                    "Frade",
                    "Fru",
                    "Frude",
                    "Gal",
                    "Gals",
                    "Gol",
                    "Gols",
                    "Hun",
                    "Huni",
                    "Hen",
                    "Heni",
                    "Klod",
                    "Klodi",
                    "Klud",
                    "Kludi",
                    "Mer",
                    "Mero",
                    "Mor",
                    "Moro",
                    "Ro",
                    "Rode",
                    "Ru",
                    "Rude",
                    "Sor",
                    "Sork",
                    "Sar",
                    "Sark",
                    "Sul",
                    "Suli",
                    "Sol",
                    "Soli",
                    "Sal",
                    "Sali",
                    "Tryn",
                    "Tryni",
                    "Tron",
                    "Troni"
                ],
                "suffix": {
                    "male": [
                        "bad",
                        "gar",
                        "gist",
                        "kar",
                        "kind",
                        "kull",
                        "pis",
                        "red",
                        "rik",
                        "till",
                        "thill",
                        "walan",
                        "vard",
                        "wig",
                        "vik"
                    ],
                    "female": [
                        "th",
                        "dith",
                        "fing",
                        "gond",
                        "hed",
                        "hedd",
                        "kild",
                        "len",
                        "mynt",
                        "mynta",
                        "nell",
                        "sta",
                        "stai",
                        "strid",
                        "thne",
                        "tilde",
                        "winda"
                    ]
                },
                "lastnames": {
                    "family": ["INGET FAMILJE NAMN"],
                    "epithets": [
                        "Vitnerdräpe",
                        "Trollhacke",
                        "Stormekrossare"
                    ],
                    "profession": [
                        "Smed",
                        "Bonde",
                        "Uppfödare",
                        "Skogshuggare"
                    ],
                    "nickname": [
                        "Klåfinger",
                        "Snenäsa",
                        "Harläpp",
                        "Trollöga"
                    ]
                }
            },
            "wildfolk": {
                "prefix": [],
                "suffix": {
                    "male": [],
                    "female": []
                }
            },
            "elf": {
                "prefix": [
                    "Harp",
                    "Jep",
                    "Jeppi",
                    "Kyll",
                    "Lep",
                    "Lepo",
                    "Norma",
                    "Normo",
                    "Pojh",
                    "Pojha",
                    "Sirp",
                    "Sirpa",
                    "Syll",
                    "Vaj",
                    "Vajne",
                    "Val",
                    "Vali"
                ],
                "suffix": {
                    "male": [
                        "hang",
                        "ehang",
                        "iaho",
                        "piaho",
                        "akka",
                        "ingas",
                        "jias",
                        "lainen",
                        "mojna",
                        "pihi",
                        "taja",
                        "ua"
                    ],
                    "female": [
                        "ala",
                        "pala",
                        "atta",
                        "hiska",
                        "ika",
                        "iulu",
                        "iullu",
                        "kosva",
                        "lajna",
                        "likki",
                        "olvi",
                        "sinka"
                    ]
                }
            },
            "dwarf": {
                "prefix": [
                    "Bor",
                    "Brok",
                    "Dvor",
                    "Fifun",
                    "Glo",
                    "Gly",
                    "Jo",
                    "Jor",
                    "Niful",
                    "Ru",
                    "Ruk",
                    "Tjeb",
                    "Tor",
                    "Zvor"
                ],
                "suffix": {
                    "male": [
                        "olgd",
                        "dolga",
                        "ka",
                        "kka",
                        "ust",
                        "rust",
                        "drank",
                        "gel",
                        "linkk",
                        "logi",
                        "rovv",
                        "van",
                        "var",
                        "zink"
                    ]
                }
            },
            "troll": {
                "prefix": [
                    "a",
                    "nak",
                    "gnak",
                    "vårt",
                    "vårta",
                    "årt",
                    "dy",
                    "dry",
                    "dryg",
                    "e",
                    "fis",
                    "fisk",
                    "ful",
                    "full",
                    "furm",
                    "gri",
                    "grik",
                    "grinn",
                    "gris",
                    "hog",
                    "ke",
                    "klo",
                    "knorr",
                    "lill",
                    "knott"
                ],
                "suffix": [
                    "lork",
                    "lorsk",
                    "lus",
                    "mo",
                    "must",
                    "ogg",
                    "päls",
                    "ryt",
                    "sno",
                    "snor",
                    "snus",
                    "stink",
                    "sto",
                    "stor",
                    "tande",
                    "tide",
                    "tov",
                    "urg",
                    "vis",
                    "yge",
                    "ygel",
                    "yt"
                ]
            }
        },
        "town": {
            "prefix": [
                "Al",
                "alfe",
                "Aske",
                "Atla",
                "Aud",
                "Audur",
                "Bjalfe",
                "Bjorn",
                "Björk",
                "Blid",
                "Blot",
                "Bock",
                "Borke",
                "Brage",
                "Brase",
                "Bronja",
                "Bål",
                "Egil",
                "Ejlög",
                "Ek",
                "Ese",
                "Fager",
                "Falk",
                "Frost",
                "Gad",
                "Galt",
                "Gaute",
                "Gerd",
                "Gisle",
                "Gno",
                "Gorm",
                "Grim",
                "Grise",
                "Gruve",
                "Grå",
                "Gyda",
                "Hamra",
                "Helga",
                "Hella",
                "Hrim",
                "Häll",
                "Jon",
                "Jorna",
                "Jot",
                "Järn",
                "Jökull",
                "Jöt",
                "Kal",
                "Kjöle",
                "Koppar",
                "Korp",
                "Kråk",
                "Kviste",
                "Laupe",
                "Lille",
                "Lo",
                "Lov",
                "Marsk",
                "Mjöd",
                "Mull",
                "Möln",
                "Nid",
                "Njal",
                "Odd",
                "Orm",
                "Ost",
                "Oster",
                "Rafner",
                "Rauk",
                "Run",
                "Ränne",
                "Silver",
                "Skuru",
                "Smed",
                "Sol",
                "Sot",
                "Starke",
                "Sten",
                "Stig",
                "Stor",
                "Storm",
                "Sund",
                "Tall",
                "Tindra",
                "Troll",
                "Tur",
                "Ulf",
                "Ulm",
                "Unn",
                "Vide",
                "Vild",
                "Vinter",
                "Vis",
                "Vit",
                "Vret",
                "Väster",
                "åker",
                "ås",
                "Älg",
                "Öst"
            ],
            "suffix": [
                "al",
                "anger",
                "backa ",
                "berg ",
                "blot",
                "bod ",
                "boda ",
                "borg",
                "botten",
                "brant",
                "bro ",
                "bruk ",
                "brunn ",
                "by ",
                "bäck ",
                "dal",
                "dis ",
                "ed",
                "fjord ",
                "fjäll ",
                "fors",
                "fors ",
                "frost ",
                "fält",
                "gang",
                "gap ",
                "gard ",
                "gull",
                "gård ",
                "haga ",
                "hall",
                "hammar ",
                "hamn ",
                "harg ",
                "hed",
                "hem",
                "holm ",
                "holt ",
                "hult",
                "häll",
                "hög ",
                "inge ",
                "klint",
                "klippan ",
                "kulla ",
                "kvarn",
                "källa ",
                "köping",
                "lev ",
                "lid ",
                "ljung ",
                "lund ",
                "lycke ",
                "löse ",
                "löv ",
                "mark ",
                "mosse",
                "mönja ",
                "nejd",
                "näs ",
                "om",
                "pass",
                "ro",
                "rum ",
                "rup ",
                "ryd ",
                "rödja ",
                "sala ",
                "skog ",
                "slaga ",
                "sorg ",
                "sta",
                "stein",
                "stena ",
                "stig",
                "stock ",
                "sund",
                "tegn ",
                "ting",
                "tjärn ",
                "tofta ",
                "topp",
                "torp ",
                "träsk ",
                "tun",
                "tune ",
                "um ",
                "vad",
                "vall",
                "vi ",
                "vik",
                "vind ",
                "virja ",
                "vy ",
                "å",
                "åker ",
                "åkra ",
                "ås ",
                "älv",
                "äng"
            ]
        },
        "tavern": {
            "prefix": [
                "troll",
                "röt",
                "orm",
                "hugg",
                "skald",
                "svin",
                "rövar",
                "mjöd",
                "hjälte",
                "korp",
                "stormes",
                "bronje",
                "tråg",
                "skogs",
                "öl",
                "mjöd",
                "tvilling",
                "härjar",
                "garm",
                "svultna",
                "lytte",
                "trasiga",
                "stegrande",
                "frusna",
                "bäcka",
                "gave",
                "saga",
                "skägg",
                "moss",
                "lav",
                "fjäll",
                "barr",
                "drak",
                "möra",
                "skummande",
                "galna",
                "uppretade",
                "slaktade",
                "lagade",
                "blå",
                "röda",
                "gröna",
                "gula",
                "vita",
                "svarta",
                "bruna",
                "försupne"
            ],
            "suffix": [
                "hallen",
                "grytet",
                "hålan",
                "stian",
                "krogen",
                "syltan",
                "svinet",
                "björnen",
                "stugan",
                "huset",
                "hålet",
                "vaken",
                "viken",
                "tjärn",
                "torp",
                "fjäll",
                "huvudet",
                "tornet",
                "korsning",
                "korsningen",
                "riket",
                "platsen",
                "punkten",
                "galten",
                "vandraren",
                "ponnyn",
                "bocken",
                "kaninen",
                "stopet",
                "hålet",
                "vaken",
                "viken",
                "tjärn",
                "torp",
                "huvudet",
                "hus",
                "katten",
                "ormen",
                "skräddaren"
            ]
        },
        "plant": {
            "prefix": [
                "Afton",
                "Alva",
                "Bergs",
                "Bjark",
                "Björn",
                "Blad",
                "Blod",
                "Blods",
                "Brons",
                "Dagg",
                "Dis",
                "Drak",
                "Dvärg",
                "Dy",
                "Eld",
                "Fackel",
                "Fager",
                "Finger",
                "Garna",
                "Gave",
                "Grim",
                "Grå",
                "Gråe",
                "Gul",
                "Gull",
                "Har",
                "Hingst",
                "Himla",
                "Hird",
                "Hjort",
                "Humle",
                "Hväle",
                "Häst",
                "Häx",
                "Igel",
                "Jarla",
                "Jord",
                "Jorn",
                "Jotun",
                "Järn",
                "Jätte",
                "Kalder",
                "Knytt",
                "Kol",
                "Koppar",
                "Korp",
                "Kungs",
                "Kärr",
                "Lom",
                "Lund",
                "Mal",
                "Manna",
                "Marsk",
                "Mist",
                "Mork",
                "Mörk",
                "Myr",
                "Mån",
                "Natt",
                "Nät",
                "Orm",
                "Ox",
                "Pil",
                "Puder",
                "Rafner",
                "Ros",
                "Röd",
                "Silver",
                "Sjö",
                "Skarp",
                "Skav",
                "Skogs",
                "Skvätt",
                "Snö",
                "Sol",
                "Sten",
                "Stjärn",
                "Stjärne",
                "Storme",
                "Svart",
                "Svin",
                "Tagg",
                "Talg",
                "Tistel",
                "Tok",
                "Troll",
                "Tråd",
                "Törn",
                "Vall",
                "Varg",
                "Vatten",
                "Vild",
                "Vinter",
                "Vit",
                "Vitner",
                "Vår",
                "Vätte",
                "Älg",
                "Älv",
                "Älva",
                "Älve",
                "Äng",
                "Änga",
                "Ängs"
            ],
            "suffix": [
                "anis",
                "apel",
                "ax",
                "bark",
                "beta",
                "bjärt",
                "blad",
                "blom",
                "blomster",
                "bräken",
                "buske",
                "bär",
                "böna",
                "cikoria",
                "dill",
                "ek",
                "en",
                "fibbla",
                "fläder",
                "frö",
                "glädje",
                "gran",
                "gäck",
                "hallon",
                "hassel",
                "hatt",
                "havre",
                "hirs",
                "hjortron",
                "klubba",
                "klöver",
                "knöl",
                "kocka",
                "koriander",
                "korn",
                "kott",
                "kotte",
                "krusbär",
                "krydda",
                "kummin",
                "kål",
                "körvel",
                "lav",
                "lilja",
                "lin",
                "lingon",
                "lök",
                "löv",
                "meliss",
                "morot",
                "mossa",
                "murkla",
                "mynta",
                "målla",
                "måra",
                "nate",
                "nässla",
                "peppar",
                "päron",
                "rabarber",
                "regn",
                "ris",
                "rot",
                "råg",
                "räfsa",
                "rättika",
                "sallad",
                "sippa",
                "själke",
                "skatta",
                "skimra",
                "skivling",
                "skräppa",
                "sköna",
                "slån",
                "smultron",
                "snår",
                "sopp",
                "sporre",
                "starr",
                "sticka",
                "stjärna",
                "storm",
                "svamp",
                "timjan",
                "torn",
                "tryffel",
                "tunga",
                "tuva",
                "törn",
                "törne",
                "ull",
                "vallmo",
                "vass",
                "vete",
                "vide",
                "viva",
                "väv",
                "ärt",
                "ärtskocka",
                "ört"
            ]
        }
    },
    "es": {
    
    },
    "fr": {
    
    }

};